query AllPosts($first: IntType = 20) {
    allPosts(orderBy: _publishedAt_DESC, first: $first) {
        title
        slug
        description
        _status
        _publishedAt
    }
    _allPostsMeta {
        count
    }
}
