compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
preferInteractive: true
yarnPath: .yarn/releases/yarn-4.0.0-rc.53.cjs
injectEnvironmentFiles:
  - .env
npmScopes:
  gsap:
    npmRegistryServer: https://npm.greensock.com
    npmAlwaysAuth: true
    npmAuthToken: ${GSAP_TOKEN}
