compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  gsap:
    npmAlwaysAuth: true
    npmAuthToken: "5ff0be9b-fb0c-4d97-986f-b3000f231de1"
    npmRegistryServer: "https://npm.greensock.com"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
