#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn pretty-quick --staged
yarn lint

branch=$(git branch | grep '*' | sed 's/* //')
if [ "$branch" = "main" ]; then
  echo "You can't commit to main"
  exit 1
fi
